from geopy import Nominatim
countries = ["Argentina",
"Australia",
"Austria",
"Azerbaijan",
"Bangladesh",
"Belarus",
"Belgium",
"Bosnia and Herzegovina",
"Bulgaria",
"Canada",
"Chile",
"China",
"Colombia",
"Costa Rica",
"Croatia",
"Cyprus",
"Czech Republic",
"Denmark",
"East Timor",
"Egypt",
"Faroe Islands",
"Finland",
"France",
"Germany",
"Ghana",
"Greece",
"Guatemala",
"Hungary",
"Iceland",
"India",
"Iran",
"Ireland",
"Israel",
"Italy",
"Japan",
"Kenya",
"South Korea",
"Macedonia",
"Latvia",
"Liberia",
"Lithuania",
"Luxembourg",
"Mexico",
"Myanmar",
"Netherlands",
"New Zealand",
"Nigeria",
"Norway",
"Pakistan",
"Palestine",
"Peru",
"Poland",
"Portugal",
"Romania",
"Russia",
"Saint Lucia",
"Serbia",
"South Africa",
"Spain",
"Sweden",
"Switzerland",
"Taiwan",
"Trinidad and Tobago",
"Turkey",
"Ukraine",
"United Kingdom",
"United States",
"Venezuela",
"Vietnam",
"Yemen"]
geolocator = Nominatim()
for country in countries:
    try:
        location = geolocator.geocode(country)
        print country + "," + str(location.latitude) + "," + str(location.longitude)
    except:
        print country